### ISSUE TITLE
Recover from teleop IK freeze

### ISSUE THREAD

**Issue by glannuzel** [pollen-robotics/reachy2-sdk-api#153]
We want to allow a safe pos to be sent at the end of teleoperation if the IK is frozen.
We could also inform the user

**Comment by jjyutm4532** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add new messages and RPC methods to handle safe position sending and IK frozen notification in the ArmService. This includes adding a SafePositionRequest message, an IKFrozenNotification message, and corresponding RPC methods in the ArmService.

You can review changes in this commit: https://github.com/jjyutm4532/pollen-robotics-reachy2-sdk-api-153/commit/c3a1eec5f7851877039a042b01ef896a84a0189d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
